PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../../../L4Re-snapshot/src/l4

TARGET                   = rot13encrypt
SRC_CC			 = server.cc
REQUIRES_LIBS            = cxx_libc_io cxx_io

include $(L4DIR)/mk/prog.mk

