PKGDIR          ?= .
L4DIR           ?= /home/trav/Projects/L4Re-snapshot/src/l4

TARGET                   = rot13encrypt-server
SRC_CC			 = server.cc
REQUIRES_LIBS            = cxx_libc_io cxx_io

include $(L4DIR)/mk/prog.mk

